// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijawvesjgyddyiymiahk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqYXd2ZXNqZ3lkZHlpeW1pYWhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MzQ2MzgsImV4cCI6MjA3MDAxMDYzOH0.ZFG9EoTGU_gar6cGnu4LYAcsfRXtQQ0yLeq7E3g0CE4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

console.log('[SupabaseClient] Supabase client initialized successfully');
console.log('[SupabaseClient] URL:', SUPABASE_URL);
console.log('[SupabaseClient] Key prefix:', SUPABASE_PUBLISHABLE_KEY.substring(0, 20) + '...');

// Test basic connectivity
supabase.from('profiles').select('count', { count: 'exact', head: true }).then(({ count, error }) => {
  if (error) {
    console.error('[SupabaseClient] Connection test failed:', error);
  } else {
    console.log('[SupabaseClient] Connection test successful. Profiles count:', count);
  }
});